# Данные для pre-trainig
pre_training_data:
  max_shard: 6542
  seed: 42
  val_split_ratio: 0.01

  # Русский язык
  rus_sources:
    - dataset_name: HuggingFaceFW/fineweb-2
      subset: rus_Cyrl
      split: train
      weight: 0.7
    - dataset_name: wikimedia/wikipedia
      subset: 20231101.ru
      split: train
      weight: 0.3
  rus_quantity: 60   # % от общего датасета
  rus_cache_docs: 1200000   #  количество документов, которые будут закешированы для ускорения обучения

  # Англиский язык
  en_sources:
    - dataset_name: HuggingFaceFW/fineweb
      split: train
      weight: 1.0
  en_quantity: 20
  en_cache_docs: 400000

  # Код
  code_sources:
    - dataset_name: HuggingFaceCode/stack-v3-train
      split: train
      weight: 1.0
  code_quantity: 20
  code_cache_docs: 400000
  
# --------------------------------------------------------------------  

# Данные для fine-tuning (SFT)
sft_data:
  seed: 42
  val_split_ratio: 0.01
  cache_docs_per_source: 200000

  sources:
    - dataset_name: concretejungles/T-Wix-instag 
      split: train
      weight: 1.0
      messages_field: messages
      filter_field: supertag
      filter_values: [code]
      cache_name: t-wix-code

    - dataset_name: concretejungles/T-Wix-instag
      split: train
      weight: 1.0
      messages_field: messages
      filter_field: supertag
      filter_values: [math, science, general-instruction, general-knowledge, writing]
      cache_name: t-wix-general

    - dataset_name: nyuuzyou/EagleSFT
      split: en
      weight: 1.0
      messages_field: messages

# ---------------------------------------------------------------------

# Данные для fine-tuning (RLFT)
rlft_data:
  rus_sources: []
  en_sources: []
  code_sources: []


