# Данные для pre-trainig
pre_training_data:
  max_shard: 6542
  seed: 42
  val_split_ratio: 0.01

  rus_sources:
    - dataset_name: HuggingFaceFW/fineweb-2
      subset: rus_Cyrl
      split: train
      weight: 0.7
    - dataset_name: wikimedia/wikipedia
      subset: 20231101.ru
      split: train
      weight: 0.3
  rus_quantity: 60   # % от общего датасета

  en_sources:
    - dataset_name: HuggingFaceFW/fineweb
      split: train
      weight: 1.0
  en_quantity: 20

  code_sources:
    - dataset_name: OpenCoder-LLM/opc-fineweb-code-corpus
      split: train
      weight: 1.0
  code_quantity: 20

  # Кеширование данных на диск
  rus_cache_docs: 3500000
  en_cache_docs: 1500000
  code_cache_docs: 2000000
  

# Данные для fine-tuning (SFT)
sft_data:
  rus_sources: []
  en_sources: []
  code_sources: []


# Данные для fine-tuning (RLFT)
rlft_data:
  rus_sources: []
  en_sources: []
  code_sources: []


