# Параметры модели 
model: 
  hidden_size: 768                  # Размер скрытого состояния модели
  num_layers: 12                    # Количество слоев в модели
  vocab_size: 65536                 # Размер словаря модели
  max_position_embeddings: 2048     # Максимальная длина последовательности, которую модель может обрабатывать
  norm_eps: 0.000001                # Epsilon для нормализации

# -----------------------------------------------------

# Параметры мехинизма внимания
attention:
  num_heads: 12                     # Количество Q голов в механизме внимания
  num_kv_heads: 4                   # Количество голов K и V в механизме внимания
  head_dim: 64                      # Размерность каждой головы внимания
  rope_theta: 10000.0               # Параметр для RoPE (Rotary Positional Embedding)
  use_qk_norm: true                 # Использовать нормализацию Q и K в механизме внимания
  qk_norm_eps: 0.000001             # Epsilon для нормализации Q и K в механизме внимания

# -----------------------------------------------------

# Параметры MLP
mlp:
  intermediate_size: 2048           # Размер промежуточного слоя в MLP


