# Конфиг для базового обучения модели
pre_treaining:
  max_len: 2048                       # длина чанков из dataloader, частая практика — начать с короткого контекста для скорости, потом дотренеровать до полного
  batch_size: 32                      # сколько последовательностей физически помещается в один forward-проход на GPU
  gradient_accumulation_steps: 4      # колько таких мини-батчей накопить перед реальным шагом оптимизатора, чтобы эффективный размер батча был больше, чем позволяет память GPU
  max_steps: 50000                    # сколько всего шагов обучения сделать
  learning_rate: 0,0003               # целевое/пиковое значение изменения весов в обучении
  warmup_steps: 1000                  # несколько первых сотен/тысяч шагов lr растёт от почти нуля до целевого значения — это защищает от нестабильности в самом начале, когда веса ещё случайные
  min_learning_rate: 0,00003          # до какого значения rl затухать
  grad_clip_norm: 1.0                 # защита от "взрыва" градиентов, максимальная норма градиента, если превышена — обрезается
  weight_decay: 0.1                   # регуляризация, штраф за слишком большие веса
  eval_interval: 500                  # как часто прогонять eval
  checkpoint_interval: 1000           # как часто сохранять чекпоинты модели в обучении


# Конфиг для тонкого обучения модели (sft)
sft:


# Конфиг для тонкого обучения модели (rlft)
rlft
